typography_spectrum: 0.13499996555037796
content_rating:
  adult: true
color:
  brandStrength: 0.985257534775883
  lightness: 0.9999968826305121
  saturation: 0.9959367157425731
  rhythmicContrast: 0.8191496224608272
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
opengraph:
  appId: 'https://www.facebook.com/ryangmccormick'
layout_spectrum: 0.12463103700429201
author:
  name: Ryan McCormick
  email: ryan@ryanmccormick.com
name: rgm_
title: Digital Ops Guy
description: ''
