typography_spectrum: 0.33691531140357256
content_rating:
  adult: true
color:
  brandStrength: 0.7985241184942424
  lightness: 0.4614710584282875
  saturation: 0.27675793692469597
  rhythmicContrast: 0.9052490515168756
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
opengraph:
  appId: 'https://www.facebook.com/ryangmccormick'
layout_spectrum: 0.8650270430371165
author:
  name: Ryan McCormick
  email: ryan@ryanmccormick.com
name: rgm_
title: Digital Ops Guy
description: Digital Ops Guy
